AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/dummy/**/*
    - gemfiles/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Documentation:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false





