test:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/sunspot_offline
    auto_commit_after_request: false
    auto_commit_after_delete_request: false
    auto_index_callback: after_commit
