name: Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      matrix:
        ruby-version: [2.6]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: 1

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ matrix.ruby-version }}-v2-${{ hashFiles('sunspot_offline.gemspec', 'Appraisals') }}
          restore-keys: |
            ${{ runner.os }}-bundle-${{ matrix.ruby-version }}-v2-

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec appraisal install --path vendor/bundle

      - name: Run tests
        run: bundle exec appraisal rake
